//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("MyOLExamModel", "FK_Auth_UserInfoCore_Auth_UserAccount", "Auth_UserAccount", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(UserManager.Framework.Model.Auth_UserAccount), "Auth_UserInfoCore", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(UserManager.Framework.Model.Auth_UserInfoCore), true)]

#endregion

namespace UserManager.Framework.Model
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class UserManagerExamEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“UserManagerExamEntities”部分中的连接字符串初始化新 UserManagerExamEntities 对象。
        /// </summary>
        public UserManagerExamEntities() : base("name=UserManagerExamEntities", "UserManagerExamEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 UserManagerExamEntities 对象。
        /// </summary>
        public UserManagerExamEntities(string connectionString) : base(connectionString, "UserManagerExamEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 UserManagerExamEntities 对象。
        /// </summary>
        public UserManagerExamEntities(EntityConnection connection) : base(connection, "UserManagerExamEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Auth_UserAccount> Auth_UserAccount
        {
            get
            {
                if ((_Auth_UserAccount == null))
                {
                    _Auth_UserAccount = base.CreateObjectSet<Auth_UserAccount>("Auth_UserAccount");
                }
                return _Auth_UserAccount;
            }
        }
        private ObjectSet<Auth_UserAccount> _Auth_UserAccount;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Auth_UserInfoCore> Auth_UserInfoCore
        {
            get
            {
                if ((_Auth_UserInfoCore == null))
                {
                    _Auth_UserInfoCore = base.CreateObjectSet<Auth_UserInfoCore>("Auth_UserInfoCore");
                }
                return _Auth_UserInfoCore;
            }
        }
        private ObjectSet<Auth_UserInfoCore> _Auth_UserInfoCore;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 Auth_UserAccount EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToAuth_UserAccount(Auth_UserAccount auth_UserAccount)
        {
            base.AddObject("Auth_UserAccount", auth_UserAccount);
        }
    
        /// <summary>
        /// 用于向 Auth_UserInfoCore EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToAuth_UserInfoCore(Auth_UserInfoCore auth_UserInfoCore)
        {
            base.AddObject("Auth_UserInfoCore", auth_UserInfoCore);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MyOLExamModel", Name="Auth_UserAccount")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Auth_UserAccount : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Auth_UserAccount 对象。
        /// </summary>
        /// <param name="userID">UserID 属性的初始值。</param>
        /// <param name="userName">UserName 属性的初始值。</param>
        /// <param name="password">Password 属性的初始值。</param>
        /// <param name="state">State 属性的初始值。</param>
        /// <param name="timeMark">TimeMark 属性的初始值。</param>
        /// <param name="applicationID">ApplicationID 属性的初始值。</param>
        public static Auth_UserAccount CreateAuth_UserAccount(global::System.Int32 userID, global::System.String userName, global::System.String password, global::System.Int32 state, global::System.Byte[] timeMark, global::System.Int32 applicationID)
        {
            Auth_UserAccount auth_UserAccount = new Auth_UserAccount();
            auth_UserAccount.UserID = userID;
            auth_UserAccount.UserName = userName;
            auth_UserAccount.Password = password;
            auth_UserAccount.State = state;
            auth_UserAccount.TimeMark = timeMark;
            auth_UserAccount.ApplicationID = applicationID;
            return auth_UserAccount;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.Int32 _State;
        partial void OnStateChanging(global::System.Int32 value);
        partial void OnStateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] TimeMark
        {
            get
            {
                return StructuralObject.GetValidValue(_TimeMark);
            }
            set
            {
                OnTimeMarkChanging(value);
                ReportPropertyChanging("TimeMark");
                _TimeMark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TimeMark");
                OnTimeMarkChanged();
            }
        }
        private global::System.Byte[] _TimeMark;
        partial void OnTimeMarkChanging(global::System.Byte[] value);
        partial void OnTimeMarkChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                OnCreateTimeChanging(value);
                ReportPropertyChanging("CreateTime");
                _CreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateTime");
                OnCreateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateTime;
        partial void OnCreateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastLoginTime
        {
            get
            {
                return _LastLoginTime;
            }
            set
            {
                OnLastLoginTimeChanging(value);
                ReportPropertyChanging("LastLoginTime");
                _LastLoginTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastLoginTime");
                OnLastLoginTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastLoginTime;
        partial void OnLastLoginTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnLastLoginTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ApplicationID
        {
            get
            {
                return _ApplicationID;
            }
            set
            {
                OnApplicationIDChanging(value);
                ReportPropertyChanging("ApplicationID");
                _ApplicationID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ApplicationID");
                OnApplicationIDChanged();
            }
        }
        private global::System.Int32 _ApplicationID;
        partial void OnApplicationIDChanging(global::System.Int32 value);
        partial void OnApplicationIDChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MyOLExamModel", "FK_Auth_UserInfoCore_Auth_UserAccount", "Auth_UserInfoCore")]
        public EntityCollection<Auth_UserInfoCore> Auth_UserInfoCore
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Auth_UserInfoCore>("MyOLExamModel.FK_Auth_UserInfoCore_Auth_UserAccount", "Auth_UserInfoCore");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Auth_UserInfoCore>("MyOLExamModel.FK_Auth_UserInfoCore_Auth_UserAccount", "Auth_UserInfoCore", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MyOLExamModel", Name="Auth_UserInfoCore")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Auth_UserInfoCore : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Auth_UserInfoCore 对象。
        /// </summary>
        /// <param name="userInfoCoreID">UserInfoCoreID 属性的初始值。</param>
        public static Auth_UserInfoCore CreateAuth_UserInfoCore(global::System.Int32 userInfoCoreID)
        {
            Auth_UserInfoCore auth_UserInfoCore = new Auth_UserInfoCore();
            auth_UserInfoCore.UserInfoCoreID = userInfoCoreID;
            return auth_UserInfoCore;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserInfoCoreID
        {
            get
            {
                return _UserInfoCoreID;
            }
            set
            {
                if (_UserInfoCoreID != value)
                {
                    OnUserInfoCoreIDChanging(value);
                    ReportPropertyChanging("UserInfoCoreID");
                    _UserInfoCoreID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserInfoCoreID");
                    OnUserInfoCoreIDChanged();
                }
            }
        }
        private global::System.Int32 _UserInfoCoreID;
        partial void OnUserInfoCoreIDChanging(global::System.Int32 value);
        partial void OnUserInfoCoreIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private Nullable<global::System.Int32> _UserID;
        partial void OnUserIDChanging(Nullable<global::System.Int32> value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RealName
        {
            get
            {
                return _RealName;
            }
            set
            {
                OnRealNameChanging(value);
                ReportPropertyChanging("RealName");
                _RealName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RealName");
                OnRealNameChanged();
            }
        }
        private global::System.String _RealName;
        partial void OnRealNameChanging(global::System.String value);
        partial void OnRealNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Sender
        {
            get
            {
                return _Sender;
            }
            set
            {
                OnSenderChanging(value);
                ReportPropertyChanging("Sender");
                _Sender = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sender");
                OnSenderChanged();
            }
        }
        private Nullable<global::System.Int32> _Sender;
        partial void OnSenderChanging(Nullable<global::System.Int32> value);
        partial void OnSenderChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Age
        {
            get
            {
                return _Age;
            }
            set
            {
                OnAgeChanging(value);
                ReportPropertyChanging("Age");
                _Age = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Age");
                OnAgeChanged();
            }
        }
        private Nullable<global::System.Int32> _Age;
        partial void OnAgeChanging(Nullable<global::System.Int32> value);
        partial void OnAgeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastModifyTime
        {
            get
            {
                return _LastModifyTime;
            }
            set
            {
                OnLastModifyTimeChanging(value);
                ReportPropertyChanging("LastModifyTime");
                _LastModifyTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModifyTime");
                OnLastModifyTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastModifyTime;
        partial void OnLastModifyTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnLastModifyTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NicName
        {
            get
            {
                return _NicName;
            }
            set
            {
                OnNicNameChanging(value);
                ReportPropertyChanging("NicName");
                _NicName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NicName");
                OnNicNameChanged();
            }
        }
        private global::System.String _NicName;
        partial void OnNicNameChanging(global::System.String value);
        partial void OnNicNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AvatarUrl
        {
            get
            {
                return _AvatarUrl;
            }
            set
            {
                OnAvatarUrlChanging(value);
                ReportPropertyChanging("AvatarUrl");
                _AvatarUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AvatarUrl");
                OnAvatarUrlChanged();
            }
        }
        private global::System.String _AvatarUrl;
        partial void OnAvatarUrlChanging(global::System.String value);
        partial void OnAvatarUrlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Birthday
        {
            get
            {
                return _Birthday;
            }
            set
            {
                OnBirthdayChanging(value);
                ReportPropertyChanging("Birthday");
                _Birthday = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Birthday");
                OnBirthdayChanged();
            }
        }
        private Nullable<global::System.DateTime> _Birthday;
        partial void OnBirthdayChanging(Nullable<global::System.DateTime> value);
        partial void OnBirthdayChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Provinceid
        {
            get
            {
                return _Provinceid;
            }
            set
            {
                OnProvinceidChanging(value);
                ReportPropertyChanging("Provinceid");
                _Provinceid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Provinceid");
                OnProvinceidChanged();
            }
        }
        private Nullable<global::System.Int32> _Provinceid;
        partial void OnProvinceidChanging(Nullable<global::System.Int32> value);
        partial void OnProvinceidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Cityid
        {
            get
            {
                return _Cityid;
            }
            set
            {
                OnCityidChanging(value);
                ReportPropertyChanging("Cityid");
                _Cityid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cityid");
                OnCityidChanged();
            }
        }
        private Nullable<global::System.Int32> _Cityid;
        partial void OnCityidChanging(Nullable<global::System.Int32> value);
        partial void OnCityidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserFrom
        {
            get
            {
                return _UserFrom;
            }
            set
            {
                OnUserFromChanging(value);
                ReportPropertyChanging("UserFrom");
                _UserFrom = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserFrom");
                OnUserFromChanged();
            }
        }
        private Nullable<global::System.Int32> _UserFrom;
        partial void OnUserFromChanging(Nullable<global::System.Int32> value);
        partial void OnUserFromChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String describe
        {
            get
            {
                return _describe;
            }
            set
            {
                OndescribeChanging(value);
                ReportPropertyChanging("describe");
                _describe = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("describe");
                OndescribeChanged();
            }
        }
        private global::System.String _describe;
        partial void OndescribeChanging(global::System.String value);
        partial void OndescribeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String qq
        {
            get
            {
                return _qq;
            }
            set
            {
                OnqqChanging(value);
                ReportPropertyChanging("qq");
                _qq = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("qq");
                OnqqChanged();
            }
        }
        private global::System.String _qq;
        partial void OnqqChanging(global::System.String value);
        partial void OnqqChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OpendValues
        {
            get
            {
                return _OpendValues;
            }
            set
            {
                OnOpendValuesChanging(value);
                ReportPropertyChanging("OpendValues");
                _OpendValues = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OpendValues");
                OnOpendValuesChanged();
            }
        }
        private global::System.String _OpendValues;
        partial void OnOpendValuesChanging(global::System.String value);
        partial void OnOpendValuesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserPoint
        {
            get
            {
                return _UserPoint;
            }
            set
            {
                OnUserPointChanging(value);
                ReportPropertyChanging("UserPoint");
                _UserPoint = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserPoint");
                OnUserPointChanged();
            }
        }
        private Nullable<global::System.Int32> _UserPoint;
        partial void OnUserPointChanging(Nullable<global::System.Int32> value);
        partial void OnUserPointChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserSpecialID
        {
            get
            {
                return _UserSpecialID;
            }
            set
            {
                OnUserSpecialIDChanging(value);
                ReportPropertyChanging("UserSpecialID");
                _UserSpecialID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserSpecialID");
                OnUserSpecialIDChanged();
            }
        }
        private global::System.String _UserSpecialID;
        partial void OnUserSpecialIDChanging(global::System.String value);
        partial void OnUserSpecialIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String QQKey
        {
            get
            {
                return _QQKey;
            }
            set
            {
                OnQQKeyChanging(value);
                ReportPropertyChanging("QQKey");
                _QQKey = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("QQKey");
                OnQQKeyChanged();
            }
        }
        private global::System.String _QQKey;
        partial void OnQQKeyChanging(global::System.String value);
        partial void OnQQKeyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WeiboKey
        {
            get
            {
                return _WeiboKey;
            }
            set
            {
                OnWeiboKeyChanging(value);
                ReportPropertyChanging("WeiboKey");
                _WeiboKey = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WeiboKey");
                OnWeiboKeyChanged();
            }
        }
        private global::System.String _WeiboKey;
        partial void OnWeiboKeyChanging(global::System.String value);
        partial void OnWeiboKeyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String QQAcessToken
        {
            get
            {
                return _QQAcessToken;
            }
            set
            {
                OnQQAcessTokenChanging(value);
                ReportPropertyChanging("QQAcessToken");
                _QQAcessToken = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("QQAcessToken");
                OnQQAcessTokenChanged();
            }
        }
        private global::System.String _QQAcessToken;
        partial void OnQQAcessTokenChanging(global::System.String value);
        partial void OnQQAcessTokenChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WeiboAcessToken
        {
            get
            {
                return _WeiboAcessToken;
            }
            set
            {
                OnWeiboAcessTokenChanging(value);
                ReportPropertyChanging("WeiboAcessToken");
                _WeiboAcessToken = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WeiboAcessToken");
                OnWeiboAcessTokenChanged();
            }
        }
        private global::System.String _WeiboAcessToken;
        partial void OnWeiboAcessTokenChanging(global::System.String value);
        partial void OnWeiboAcessTokenChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MyOLExamModel", "FK_Auth_UserInfoCore_Auth_UserAccount", "Auth_UserAccount")]
        public Auth_UserAccount Auth_UserAccount
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Auth_UserAccount>("MyOLExamModel.FK_Auth_UserInfoCore_Auth_UserAccount", "Auth_UserAccount").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Auth_UserAccount>("MyOLExamModel.FK_Auth_UserInfoCore_Auth_UserAccount", "Auth_UserAccount").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Auth_UserAccount> Auth_UserAccountReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Auth_UserAccount>("MyOLExamModel.FK_Auth_UserInfoCore_Auth_UserAccount", "Auth_UserAccount");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Auth_UserAccount>("MyOLExamModel.FK_Auth_UserInfoCore_Auth_UserAccount", "Auth_UserAccount", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
